import { useState, useEffect, useCallback, useMemo } from 'react'
import { Theme } from '@astryxdesign/core/theme'
import { neutralTheme } from '@astryxdesign/theme-neutral/built'
import type { Idea, MonthlyData, Category, Collection, ViewMode, PageTab } from './types'

import { NavBar } from './components/NavBar'
import { HeroSection } from './components/HeroSection'
import { StatsBar } from './components/StatsBar'
import { FilterBar } from './components/FilterBar'
import { IdeaGrid } from './components/IdeaGrid'
import { IdeaDetail } from './components/IdeaDetail'
import { NicheGrid } from './components/NicheGrid'
import { NicheDetail } from './components/NicheDetail'
import { JobGrid } from './components/JobGrid'
import { JobDetail } from './components/JobDetail'
import { TradingGrid } from './components/TradingGrid'
import { TradingDetail } from './components/TradingDetail'
import { AgentChat } from './components/AgentChat'
import { Footer } from './components/Footer'
import { formatArchiveDate, formatArchiveMonth } from './lib/date'
import { decodeFilters, decodeRoute, encodeRoute, isFiltered as checkFiltered } from './lib/url'

const FALLBACK_MONTHS = ['2026-07', '2026-06']

interface DataManifest {
  months: string[]
}

function isDataManifest(value: unknown): value is DataManifest {
  return (
    typeof value === 'object' &&
    value !== null &&
    'months' in value &&
    Array.isArray(value.months) &&
    value.months.every(month => typeof month === 'string' && /^\d{4}-\d{2}$/.test(month))
  )
}

type ThemeMode = 'light' | 'dark' | 'system'

function nextTheme(mode: ThemeMode): ThemeMode {
  return mode === 'system' ? 'dark' : mode === 'dark' ? 'light' : 'system'
}

function resolveMode(mode: ThemeMode): 'light' | 'dark' {
  if (mode === 'system') {
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
  }
  return mode
}

function loadCollections(): Collection[] {
  try {
    return JSON.parse(localStorage.getItem('ia-collections') || '[]')
  } catch { return [] }
}

export default function App() {
  const [ideas, setIdeas]    = useState<Idea[]>([])
  const [loading, setLoading] = useState(true)
  const initialRoute = useMemo(() => decodeRoute(), [])
  const [activeTab, setActiveTab] = useState<PageTab>(initialRoute.tab)

  // Read initial filters from URL (for share links)
  const initialFilters = useMemo(() => decodeFilters(), [])

  const [monthFilter,  setMonthFilter]  = useState(initialFilters.monthFilter)
  const [catFilter,    setCatFilter]    = useState(initialFilters.catFilter)
  const [regionFilter, setRegionFilter] = useState(initialFilters.regionFilter)
  const [sourceFilter, setSourceFilter] = useState(initialFilters.sourceFilter)
  const [searchQuery,  setSearchQuery]  = useState(initialFilters.searchQuery)
  const [bestOnly,     setBestOnly]     = useState(initialFilters.bestOnly)
  const [viewMode,     setViewMode]     = useState<ViewMode>('grid')

  const [themeMode, setThemeMode] = useState<ThemeMode>(() => {
    try { return (localStorage.getItem('ia-theme') as ThemeMode) || 'system' } catch { return 'system' }
  })

  const [collections, setCollections] = useState<Collection[]>(loadCollections)
  const [selectedCollection, setSelectedCollection] = useState<string | null>(null)

  const [selectedDetailId, setSelectedDetailId] = useState<string | null>(initialRoute.detailId)

  const updateRoute = useCallback((tab: PageTab, detailId: string | null, replace = false) => {
    const url = `${window.location.pathname}${window.location.search}${encodeRoute(tab, detailId)}`
    window.history[replace ? 'replaceState' : 'pushState'](null, '', url)
  }, [])

  useEffect(() => {
    const syncRouteFromLocation = () => {
      const route = decodeRoute()
      setActiveTab(route.tab)
      setSelectedDetailId(route.detailId)
    }

    window.addEventListener('popstate', syncRouteFromLocation)
    window.addEventListener('hashchange', syncRouteFromLocation)
    return () => {
      window.removeEventListener('popstate', syncRouteFromLocation)
      window.removeEventListener('hashchange', syncRouteFromLocation)
    }
  }, [])

  // Load all monthly archives in parallel. The manifest is generated by sync-data.mjs.
  useEffect(() => {
    const controller = new AbortController()

    async function load() {
      setLoading(true)
      try {
        const manifestResponse = await fetch('data/index.json', { signal: controller.signal })
        const manifest = manifestResponse.ok
          ? await manifestResponse.json()
          : null
        const months = isDataManifest(manifest) ? manifest.months : FALLBACK_MONTHS

        const monthlyResults = await Promise.allSettled(
          months.map(async month => {
            const response = await fetch(`data/${month}.json`, { signal: controller.signal })
            if (!response.ok) throw new Error(`${month}: HTTP ${response.status}`)
            const data: MonthlyData = await response.json()
            return data.ideas ?? []
          }),
        )
        const all = monthlyResults.flatMap(result => result.status === 'fulfilled' ? result.value : [])

        let starredIds = new Set<string>()
        try {
          starredIds = new Set(JSON.parse(localStorage.getItem('ia-stars') || '[]'))
        } catch { /* ignore malformed local data */ }

        setIdeas(all.map(idea => ({
          ...idea,
          status: starredIds.has(idea.id) ? 'starred' : idea.status,
        })))
      } catch (error) {
        if (!controller.signal.aborted) {
          console.error('Échec du chargement de l’archive', error)
          setIdeas([])
        }
      } finally {
        if (!controller.signal.aborted) setLoading(false)
      }
    }

    void load()
    return () => controller.abort()
  }, [])

  // Theme persistence
  useEffect(() => {
    try { localStorage.setItem('ia-theme', themeMode) } catch { /* ignore */ }
  }, [themeMode])

  const handleThemeToggle = useCallback(() => {
    setThemeMode(m => nextTheme(m))
  }, [])

  // Persist collections
  useEffect(() => {
    try { localStorage.setItem('ia-collections', JSON.stringify(collections)) } catch { /* ignore */ }
  }, [collections])

  // Star toggle
  const toggleStar = useCallback((id: string) => {
    setIdeas(prev => {
      const next = prev.map(i =>
        i.id !== id ? i : { ...i, status: (i.status === 'starred' ? 'pending' : 'starred') as 'pending' | 'starred' }
      )
      const starred = next.filter(i => i.status === 'starred').map(i => i.id)
      try { localStorage.setItem('ia-stars', JSON.stringify(starred)) } catch { /* ignore */ }
      return next
    })
  }, [])

  // Reset all filters
  const resetFilters = useCallback(() => {
    setMonthFilter('all')
    setCatFilter('all')
    setRegionFilter('all')
    setSourceFilter('all')
    setSearchQuery('')
    setBestOnly(false)
    setSelectedCollection(null)
  }, [])

  // Collections CRUD
  const createCollection = useCallback((name: string) => {
    const col: Collection = {
      id: `col-${Date.now()}`,
      name,
      ideaIds: [],
      createdAt: Date.now(),
    }
    setCollections(prev => [...prev, col])
  }, [])

  const addToCollection = useCallback((ideaId: string, colId: string) => {
    setCollections(prev =>
      prev.map(c => c.id !== colId ? c : {
        ...c,
        ideaIds: c.ideaIds.includes(ideaId) ? c.ideaIds : [...c.ideaIds, ideaId],
      })
    )
  }, [])

  // Split by source
  const ideasOnly = useMemo(() => ideas.filter(i =>
    i.source === 'idees-matin' || i.source === 'self-improving'
  ), [ideas])
  const nichesOnly = useMemo(() => ideas.filter(i => i.source === 'scan-niches'), [ideas])
  const jobsOnly = useMemo(() => ideas.filter(i => i.source === 'freelance'), [ideas])
  const tradingOnly = useMemo(() => ideas.filter(i => i.source === 'trading'), [ideas])

  // Get active pool
  const activePool = useMemo(() => {
    switch (activeTab) {
      case 'niches': return nichesOnly
      case 'jobs': return jobsOnly
      case 'trading': return tradingOnly
      default: return ideasOnly
    }
  }, [activeTab, ideasOnly, nichesOnly, jobsOnly, tradingOnly])

  const selectedDetail = useMemo(
    () => selectedDetailId && activePool.some(idea => idea.id === selectedDetailId)
      ? ideas.find(idea => idea.id === selectedDetailId) ?? null
      : null,
    [ideas, activePool, selectedDetailId],
  )
  const detailIdea = activeTab === 'ideas' ? selectedDetail : null
  const detailNiche = activeTab === 'niches' ? selectedDetail : null
  const detailJob = activeTab === 'jobs' ? selectedDetail : null
  const detailTrading = activeTab === 'trading' ? selectedDetail : null

  // Filter
  const filtered = useMemo(() => {
    let pool = activePool

    if (selectedCollection) {
      const col = collections.find(c => c.id === selectedCollection)
      if (col) pool = pool.filter(i => col.ideaIds.includes(i.id))
    }

    return pool.filter(i => {
      if (monthFilter  !== 'all' && i.date.substring(0, 7) !== monthFilter)   return false
      if (catFilter    !== 'all' && i.category  !== (catFilter as Category))  return false
      if (regionFilter !== 'all' && i.region    !== regionFilter)             return false
      if (sourceFilter !== 'all' && i.source    !== sourceFilter)             return false
      if (bestOnly && i.status !== 'starred')                                 return false
      if (searchQuery) {
        const q = searchQuery.toLowerCase()
        const haystack = [i.title, i.description, i.problem, i.market, i.stack, i.theme]
          .filter(Boolean).join(' ').toLowerCase()
        if (!haystack.includes(q)) return false
      }
      return true
    })
  }, [activePool, monthFilter, catFilter, regionFilter, sourceFilter, bestOnly, searchQuery, selectedCollection, collections])

  // Group ideas by month (for ideas tab only)
  const { grouped, groupKeys } = useMemo(() => {
    const grouped = filtered.reduce<Record<string, Idea[]>>((acc, idea) => {
      const m = idea.date.substring(0, 7)
      if (!acc[m]) acc[m] = []
      acc[m].push(idea)
      return acc
    }, {})
    const groupKeys = Object.keys(grouped).sort().reverse()
    return { grouped, groupKeys }
  }, [filtered])

  // Stats
  const stats = useMemo(() => ({
    total:   ideasOnly.length,
    starred: ideasOnly.filter(i => i.status === 'starred').length,
    mada:    ideasOnly.filter(i => i.region === 'madagascar').length,
    global:  ideasOnly.filter(i => i.region === 'global').length,
  }), [ideasOnly])

  const nicheStats = useMemo(() => ({
    total: nichesOnly.length,
    starred: nichesOnly.filter(i => i.status === 'starred').length,
    thisMonth: nichesOnly.filter(i => i.date.substring(0, 7) === '2026-07').length,
  }), [nichesOnly])

  const jobStats = useMemo(() => ({
    total: jobsOnly.length,
    starred: jobsOnly.filter(i => i.status === 'starred').length,
    thisMonth: jobsOnly.filter(i => i.date.substring(0, 7) === '2026-07').length,
  }), [jobsOnly])

  const tradingStats = useMemo(() => ({
    total: tradingOnly.length,
    starred: tradingOnly.filter(i => i.status === 'starred').length,
    thisMonth: tradingOnly.filter(i => i.date.substring(0, 7) === '2026-07').length,
  }), [tradingOnly])

  const availableMonths = useMemo(
    () => [...new Set(ideas.map(i => i.date.substring(0, 7)))].sort().reverse(),
    [ideas],
  )

  const filterState = useMemo(
    () => ({ monthFilter, catFilter, regionFilter, sourceFilter, searchQuery, bestOnly }),
    [monthFilter, catFilter, regionFilter, sourceFilter, searchQuery, bestOnly],
  )

  const hasFilters = useMemo(() => checkFiltered(filterState), [filterState])

  // Detail navigation for ideas
  const flatFiltered = useMemo(
    () => groupKeys.flatMap(k => grouped[k] ?? []).sort((a, b) => b.date.localeCompare(a.date)),
    [grouped, groupKeys],
  )

  const detailIdx = useMemo(
    () => detailIdea ? flatFiltered.findIndex(i => i.id === detailIdea.id) : -1,
    [detailIdea, flatFiltered],
  )

  // Niche detail navigation
  const nicheFlatList = useMemo(
    () => [...nichesOnly].sort((a, b) => b.date.localeCompare(a.date)),
    [nichesOnly],
  )

  const nicheIdx = useMemo(
    () => detailNiche ? nicheFlatList.findIndex(i => i.id === detailNiche.id) : -1,
    [detailNiche, nicheFlatList],
  )

  // Job detail navigation
  const jobFlatList = useMemo(
    () => [...jobsOnly].sort((a, b) => b.date.localeCompare(a.date)),
    [jobsOnly],
  )

  const jobIdx = useMemo(
    () => detailJob ? jobFlatList.findIndex(i => i.id === detailJob.id) : -1,
    [detailJob, jobFlatList],
  )

  // Trading detail navigation
  const tradingFlatList = useMemo(
    () => [...tradingOnly].sort((a, b) => b.date.localeCompare(a.date)),
    [tradingOnly],
  )

  const tradingIdx = useMemo(
    () => detailTrading ? tradingFlatList.findIndex(i => i.id === detailTrading.id) : -1,
    [detailTrading, tradingFlatList],
  )

  const openDetail = useCallback((idea: Idea) => {
    setSelectedDetailId(idea.id)
    updateRoute(activeTab, idea.id)
  }, [activeTab, updateRoute])
  const closeDetail = useCallback(() => {
    setSelectedDetailId(null)
    updateRoute(activeTab, null)
  }, [activeTab, updateRoute])
  const navigateDetail = useCallback((idea: Idea) => {
    setSelectedDetailId(idea.id)
    updateRoute(activeTab, idea.id)
  }, [activeTab, updateRoute])

  const openNicheDetail = openDetail
  const closeNicheDetail = closeDetail
  const navigateNiche = navigateDetail

  const openJobDetail = openDetail
  const closeJobDetail = closeDetail
  const navigateJob = navigateDetail

  const openTradingDetail = openDetail
  const closeTradingDetail = closeDetail
  const navigateTrading = navigateDetail

  const prevIdea = detailIdx > 0 ? flatFiltered[detailIdx - 1] : null
  const nextIdea = detailIdx < flatFiltered.length - 1 ? flatFiltered[detailIdx + 1] : null
  const prevNiche = nicheIdx > 0 ? nicheFlatList[nicheIdx - 1] : null
  const nextNiche = nicheIdx < nicheFlatList.length - 1 ? nicheFlatList[nicheIdx + 1] : null
  const prevJob = jobIdx > 0 ? jobFlatList[jobIdx - 1] : null
  const nextJob = jobIdx < jobFlatList.length - 1 ? jobFlatList[jobIdx + 1] : null
  const prevTrading = tradingIdx > 0 ? tradingFlatList[tradingIdx - 1] : null
  const nextTrading = tradingIdx < tradingFlatList.length - 1 ? tradingFlatList[tradingIdx + 1] : null

  const handleTabChange = useCallback((tab: PageTab) => {
    setActiveTab(tab)
    setSelectedDetailId(null)
    resetFilters()
    updateRoute(tab, null)
  }, [resetFilters, updateRoute])

  const resolvedMode = resolveMode(themeMode)

  // Render active tab content
  const renderTabContent = () => {
    switch (activeTab) {
      case 'niches':
        return (
          <>
            <div className="section-header">
              <div>
                <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(1.8rem, 4vw, 2.4rem)', fontWeight: 400, margin: 0, letterSpacing: '-0.01em', color: 'var(--color-text-primary)' }}>
                  Niches Business
                </h1>
                <p style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--color-text-secondary)', margin: '6px 0 0' }}>
                  Analyses hebdomadaires des opportunités de marché
                </p>
              </div>
              <div className="section-summary">
                <span><span className="counter-num">{nicheStats.total}</span> niches</span>
                {nicheStats.starred > 0 && <span><span className="counter-num">{nicheStats.starred}</span> favoris</span>}
                <span><span className="counter-num">{nicheStats.thisMonth}</span> ce mois</span>
              </div>
            </div>
            <FilterBar
              ideas={nichesOnly}
              monthFilter={monthFilter} catFilter={catFilter} regionFilter={regionFilter} sourceFilter={sourceFilter}
              searchQuery={searchQuery} bestOnly={bestOnly} viewMode={viewMode}
              collections={collections} selectedCollection={selectedCollection}
              onMonthChange={setMonthFilter} onCatChange={setCatFilter} onRegionChange={setRegionFilter} onSourceChange={setSourceFilter}
              onSearchChange={setSearchQuery} onBestToggle={() => setBestOnly(b => !b)} onViewModeChange={setViewMode}
              onResetFilters={resetFilters} onCollectionCreate={createCollection} onCollectionSelect={setSelectedCollection}
              availableMonths={availableMonths} filteredCount={filtered.length} isFiltered={hasFilters || selectedCollection !== null}
              activeTab={activeTab}
            />
            <NicheGrid niches={filtered} toggleStar={toggleStar} formatDate={formatArchiveDate} onOpenDetail={openNicheDetail} isFiltered={hasFilters} loading={loading} />
          </>
        )
      case 'jobs':
        return (
          <>
            <div className="section-header">
              <div>
                <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(1.8rem, 4vw, 2.4rem)', fontWeight: 400, margin: 0, letterSpacing: '-0.01em', color: 'var(--color-text-primary)' }}>
                  Emplois Tech
                </h1>
                <p style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--color-text-secondary)', margin: '6px 0 0' }}>
                  Missions freelance, CDI et stages pour développeurs
                </p>
              </div>
              <div className="section-summary">
                <span><span className="counter-num">{jobStats.total}</span> offres</span>
                {jobStats.starred > 0 && <span><span className="counter-num">{jobStats.starred}</span> favoris</span>}
                <span><span className="counter-num">{jobStats.thisMonth}</span> ce mois</span>
              </div>
            </div>
            <FilterBar
              ideas={jobsOnly}
              monthFilter={monthFilter} catFilter={catFilter} regionFilter={regionFilter} sourceFilter={sourceFilter}
              searchQuery={searchQuery} bestOnly={bestOnly} viewMode={viewMode}
              collections={collections} selectedCollection={selectedCollection}
              onMonthChange={setMonthFilter} onCatChange={setCatFilter} onRegionChange={setRegionFilter} onSourceChange={setSourceFilter}
              onSearchChange={setSearchQuery} onBestToggle={() => setBestOnly(b => !b)} onViewModeChange={setViewMode}
              onResetFilters={resetFilters} onCollectionCreate={createCollection} onCollectionSelect={setSelectedCollection}
              availableMonths={availableMonths} filteredCount={filtered.length} isFiltered={hasFilters || selectedCollection !== null}
              activeTab={activeTab}
            />
            <JobGrid jobs={filtered} toggleStar={toggleStar} formatDate={formatArchiveDate} onOpenDetail={openJobDetail} isFiltered={hasFilters} loading={loading} />
          </>
        )
      case 'trading':
        return (
          <>
            <div className="section-header">
              <div>
                <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(1.8rem, 4vw, 2.4rem)', fontWeight: 400, margin: 0, letterSpacing: '-0.01em', color: 'var(--color-text-primary)' }}>
                  Stratégies Trading
                </h1>
                <p style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--color-text-secondary)', margin: '6px 0 0' }}>
                  Analyses SMC/OTE, backtests et opportunités de marché
                </p>
              </div>
              <div className="section-summary">
                <span><span className="counter-num">{tradingStats.total}</span> stratégies</span>
                {tradingStats.starred > 0 && <span><span className="counter-num">{tradingStats.starred}</span> favoris</span>}
                <span><span className="counter-num">{tradingStats.thisMonth}</span> ce mois</span>
              </div>
            </div>
            <FilterBar
              ideas={tradingOnly}
              monthFilter={monthFilter} catFilter={catFilter} regionFilter={regionFilter} sourceFilter={sourceFilter}
              searchQuery={searchQuery} bestOnly={bestOnly} viewMode={viewMode}
              collections={collections} selectedCollection={selectedCollection}
              onMonthChange={setMonthFilter} onCatChange={setCatFilter} onRegionChange={setRegionFilter} onSourceChange={setSourceFilter}
              onSearchChange={setSearchQuery} onBestToggle={() => setBestOnly(b => !b)} onViewModeChange={setViewMode}
              onResetFilters={resetFilters} onCollectionCreate={createCollection} onCollectionSelect={setSelectedCollection}
              availableMonths={availableMonths} filteredCount={filtered.length} isFiltered={hasFilters || selectedCollection !== null}
              activeTab={activeTab}
            />
            <TradingGrid strategies={filtered} toggleStar={toggleStar} formatDate={formatArchiveDate} onOpenDetail={openTradingDetail} isFiltered={hasFilters} loading={loading} />
          </>
        )
      default: // ideas
        return (
          <>
            <HeroSection totalIdeas={ideasOnly.length} />
            <div style={{ maxWidth: 'var(--app-max-width)', margin: '0 auto', padding: '0 20px' }}>
              <StatsBar stats={stats} />
              <FilterBar
                ideas={ideasOnly}
                monthFilter={monthFilter} catFilter={catFilter} regionFilter={regionFilter} sourceFilter={sourceFilter}
                searchQuery={searchQuery} bestOnly={bestOnly} viewMode={viewMode}
                collections={collections} selectedCollection={selectedCollection}
                onMonthChange={setMonthFilter} onCatChange={setCatFilter} onRegionChange={setRegionFilter} onSourceChange={setSourceFilter}
                onSearchChange={setSearchQuery} onBestToggle={() => setBestOnly(b => !b)} onViewModeChange={setViewMode}
                onResetFilters={resetFilters} onCollectionCreate={createCollection} onCollectionSelect={setSelectedCollection}
                availableMonths={availableMonths} filteredCount={filtered.length} isFiltered={hasFilters || selectedCollection !== null}
                activeTab={activeTab}
              />
              <IdeaGrid
                groups={grouped} groupKeys={groupKeys} toggleStar={toggleStar}
                formatMonth={formatArchiveMonth} formatDate={formatArchiveDate} loading={loading}
                viewMode={viewMode} isFiltered={hasFilters} onOpenDetail={openDetail}
                collections={collections} onAddToCollection={addToCollection}
              />
            </div>
          </>
        )
    }
  }

  return (
    <Theme theme={neutralTheme} mode={resolvedMode}>
      <div style={{ minHeight: '100vh', background: 'var(--color-background-body)' }}>
        <NavBar
          themeMode={themeMode}
          onThemeToggle={handleThemeToggle}
          activeTab={activeTab}
          onTabChange={handleTabChange}
          ideaCount={ideasOnly.length}
          nicheCount={nichesOnly.length}
          jobCount={jobsOnly.length}
          tradingCount={tradingOnly.length}
        />

        <main>
          <div style={{ maxWidth: 'var(--app-max-width)', margin: '0 auto', padding: '0 20px' }}>
            {renderTabContent()}
          </div>
        </main>

        <Footer />
        <AgentChat ideas={ideas} />

        {detailIdea && (
          <IdeaDetail
            idea={detailIdea} prevIdea={prevIdea} nextIdea={nextIdea}
            onClose={closeDetail} onNavigate={navigateDetail}
            toggleStar={toggleStar} formatDate={formatArchiveDate}
          />
        )}
        {detailNiche && (
          <NicheDetail
            niche={detailNiche} prevNiche={prevNiche} nextNiche={nextNiche}
            onClose={closeNicheDetail} onNavigate={navigateNiche}
            toggleStar={toggleStar} formatDate={formatArchiveDate}
          />
        )}
        {detailJob && (
          <JobDetail
            job={detailJob} prevJob={prevJob} nextJob={nextJob}
            onClose={closeJobDetail} onNavigate={navigateJob}
            toggleStar={toggleStar} formatDate={formatArchiveDate}
          />
        )}
        {detailTrading && (
          <TradingDetail
            strategy={detailTrading} prevStrategy={prevTrading} nextStrategy={nextTrading}
            onClose={closeTradingDetail} onNavigate={navigateTrading}
            toggleStar={toggleStar} formatDate={formatArchiveDate}
          />
        )}
      </div>
    </Theme>
  )
}
